image: node:latest

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - init
  - build
  - tests
  - deploy

init:
  stage: init
  script:
    - rm -rf node_modules
    - npm install

build:
  stage: build
  script:
    - npm run-script build
  artifacts:
    expire_in: '60 sec'
    paths:
      - dist/
    
tests:
  stage: tests
  script:
    - npm test
  dependencies:
    - build

deploy:
  stage: deploy
  dependencies:
    - build
  image: docker:git
  services:
  - docker:dind
  # variables:
  #   DOCKER_DRIVER: overlay
  before_script:
    - docker info
    - rm -rf node_modules
    - npm ci --only=production
  script:
    - docker build -t registry.myeggo.com/3rd-parties/sizecharter .
    - docker push registry.myeggo.com/3rd-parties/sizecharter

  